### ISSUE TITLE
angular starter not working

### ISSUE THREAD

**Issue by tahir-jamil** [PatrickJS/angular-starter#2050]
hey i have just follow these steps and trying to run the application by its not working for me 
https://github.com/gdi2290/angular-starter#installing

1. fork this repo
2. clone your fork
3. npm install webpack-dev-server rimraf webpack -g to install required global dependencies
4. npm install to install all dependencies or yarn
5. npm run server to start the dev server in another tab

> hear are the error logs 
```
Muhammads-MBP:angular-starter m.tahir$ npm run server

> angular-starter@7.5.0 server /Users/m.tahir/projects/angular-starter
> npm run server:dev


> angular-starter@7.5.0 server:dev /Users/m.tahir/projects/angular-starter
> npm run webpack-dev-server -- --config config/webpack.dev.js --open --progress --profile --watch --content-base src/


> angular-starter@7.5.0 webpack-dev-server /Users/m.tahir/projects/angular-starter
> node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js "--config" "config/webpack.dev.js" "--open" "--progress" "--profile" "--watch" "--content-base" "src/"

 10% building 2/2 modules 0 active⚠ ｢wds｣: The `setup` option is deprecated and will be removed in v3. Please update your config to use `before`
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1505:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-starter@7.5.0 webpack-dev-server: `node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js "--config" "config/webpack.dev.js" "--open" "--progress" "--profile" "--watch" "--content-base" "src/"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-starter@7.5.0 webpack-dev-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/m.tahir/.npm/_logs/2018-12-12T17_41_22_241Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-starter@7.5.0 server:dev: `npm run webpack-dev-server -- --config config/webpack.dev.js --open --progress --profile --watch --content-base src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-starter@7.5.0 server:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/m.tahir/.npm/_logs/2018-12-12T17_41_22_863Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-starter@7.5.0 server: `npm run server:dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-starter@7.5.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/m.tahir/.npm/_logs/2018-12-12T17_41_22_893Z-debug.log
Muhammads-MBP:angular-starter m.tahir$ npm run server

> angular-starter@7.5.0 server /Users/m.tahir/projects/angular-starter
> npm run server:dev


> angular-starter@7.5.0 server:dev /Users/m.tahir/projects/angular-starter
> npm run webpack-dev-server -- --config config/webpack.dev.js --open --progress --profile --watch --content-base src/


> angular-starter@7.5.0 webpack-dev-server /Users/m.tahir/projects/angular-starter
> node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js "--config" "config/webpack.dev.js" "--open" "--progress" "--profile" "--watch" "--content-base" "src/"

 10% building 2/2 modules 0 active⚠ ｢wds｣: The `setup` option is deprecated and will be removed in v3. Please update your config to use `before`
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1505:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-starter@7.5.0 webpack-dev-server: `node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js "--config" "config/webpack.dev.js" "--open" "--progress" "--profile" "--watch" "--content-base" "src/"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-starter@7.5.0 webpack-dev-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/m.tahir/.npm/_logs/2018-12-12T17_49_07_150Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-starter@7.5.0 server:dev: `npm run webpack-dev-server -- --config config/webpack.dev.js --open --progress --profile --watch --content-base src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-starter@7.5.0 server:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/m.tahir/.npm/_logs/2018-12-12T17_49_07_176Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-starter@7.5.0 server: `npm run server:dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-starter@7.5.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/m.tahir/.npm/_logs/2018-12-12T17_49_07_200Z-debug.log
Muhammads-MBP:angular-starter m.tahir$ 

```

**Comment by tahir-jamil** [comment]
hey i have build the project using webpack and using tomcat server i try to open the dist project and hear are the error logs please help about it 
![screen shot 2018-12-17 at 2 02 14 pm](https://user-images.githubusercontent.com/40952630/50076821-840bc780-0204-11e9-8e6c-4be075d5b92b.png)

**Comment by thanhdevapp** [comment]
same problem

**Comment by tahir-jamil** [comment]
Close due to inactivity
